services:
  prod:
    image: gcr.io/project-digital-admedika/adbrief-prod:1.0.0
    container_name: adbrief-fe
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      platforms:
        - linux/amd64
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - PORT=4173
    env_file:
      - .env.prod
  staging:
    image: gcr.io/project-digital-admedika/adbrief-staging:1.0.0
    container_name: adbrief-fe
    build:
      context: .
      dockerfile: Dockerfile
      target: staging
      platforms:
        - linux/amd64
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=staging
      - PORT=4173
    env_file:
      - .env.staging
  dev:
    image: gcr.io/project-digital-admedika/adbrief-dev:1.0.0
    container_name: adbrief-fe
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      platforms:
        - linux/amd64
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=developement
      - PORT=4173
    env_file:
      - .env.dev
